a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

print("a < b and b > c: ", a < b and b > c)
print("a > b or b > c: ", a > b or b > c)
print("a == b: ", a == b)
print("a != b: ", a != b)
print("a >= b: ", a >= b)
print("a <= b: ", a <= b)
print("a > b: ", a > b)
print("a < b: ", a < b)
print("a is b: ", a is b)
print("a is not b: ", a is not b)